### ISSUE TITLE
cant connect to ws://51.15.127.80:14808

### ISSUE THREAD

**Issue by krekel1** [VatsaDev/Mineuino#1]
cant connect and cant mine ws://51.15.127.80:14808
what to do next??? i tried many different things all do not work

**Comment by mankalan** [comment]
Mee to, also with https.

**Comment by oxmc** [comment]
@mankalan @krekel1 Theres a fork of this project that has that fixed: [Duinotize](https://github.com/mobilegmYT/Duinotize)
